In [2]:
# Data frames.
import pandas as pd

# Plotting.
import seaborn as sns

# Stats.
import scipy.stats as ss

# Numerical arrays.
import numpy as np

# Collections.
import collections as co

# Specials.
import scipy.special as spec


# For plotting 
import plotly as py
import plotly.graph_objects as go
from plotly.offline import iplot
import plotly.express as px

In [3]:
Diet = pd.read_csv(r'C:\Users\User\Desktop\repo\Machine-learning-and-Statistics\Scipy Stats\Diet_R.csv')
Diet

    Person gender  Age  Height  pre.weight  Diet  weight6weeks  Weight loss
0       25          41     171          60     2          60.0          0.0
1       26          32     174         103     2         103.0          0.0
2        1      0   22     159          58     1          54.2          3.8
3        2      0   46     192          60     1          54.0          6.0
4        3      0   55     170          64     1          63.3          0.7
..     ...    ...  ...     ...         ...   ...           ...          ...
73      74      1   35     183          83     3          80.2          2.8
74      75      1   49     177          84     3          79.9          4.1
75      76      1   28     164          85     3          79.7          5.3
76      77      1   40     167          87     3          77.8          9.2
77      78      1   51     175          88     3          81.9          6.1

[78 rows x 8 columns]

In [4]:
Diet.dtypes

Person            int64
gender           object
Age               int64
Height            int64
pre.weight        int64
Diet              int64
weight6weeks    float64
Weight loss     float64
dtype: object

In [ ]:
Diet.groupby("Diet")['Weight loss'].describe()

In [5]:
Diet1 = Diet[(Diet['Diet'] == '1')]
Diet2 = Diet[(Diet['Diet'] == '2')]

In [6]:
from scipy import stats

stats.shapiro(Diet1['Weight loss'])
stats.shapiro(Diet2['Weight loss'])

ValueError: Data must be at least length 3.